default:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - package
  - deploy

job1:
  stage: build
  script:
    - dotnet build

job2:
  stage: deploy
  script:
    - dotnet publish -c Release -o publish